package io.vulpine.lib.fa;

import javafx.scene.text.Font;

/**
 * FontAwesome Regular Glyph Index
 *
 * https://fontawesome.com
 * @version v5.0.13
 */
public enum FARegularGlyph implements FAGlyph
{
  FA_ADDRESS_BOOK("\uf2b9"),
  FA_ADDRESS_CARD("\uf2bb"),
  FA_ARROW_ALT_CIRCLE_DOWN("\uf358"),
  FA_ARROW_ALT_CIRCLE_LEFT("\uf359"),
  FA_ARROW_ALT_CIRCLE_RIGHT("\uf35a"),
  FA_ARROW_ALT_CIRCLE_UP("\uf35b"),
  FA_BELL("\uf0f3"),
  FA_BELL_SLASH("\uf1f6"),
  FA_BOOKMARK("\uf02e"),
  FA_BUILDING("\uf1ad"),
  FA_CALENDAR("\uf133"),
  FA_CALENDAR_ALT("\uf073"),
  FA_CALENDAR_CHECK("\uf274"),
  FA_CALENDAR_MINUS("\uf272"),
  FA_CALENDAR_PLUS("\uf271"),
  FA_CALENDAR_TIMES("\uf273"),
  FA_CARET_SQUARE_DOWN("\uf150"),
  FA_CARET_SQUARE_LEFT("\uf191"),
  FA_CARET_SQUARE_RIGHT("\uf152"),
  FA_CARET_SQUARE_UP("\uf151"),
  FA_CHART_BAR("\uf080"),
  FA_CHECK_CIRCLE("\uf058"),
  FA_CHECK_SQUARE("\uf14a"),
  FA_CIRCLE("\uf111"),
  FA_CLIPBOARD("\uf328"),
  FA_CLOCK("\uf017"),
  FA_CLONE("\uf24d"),
  FA_CLOSED_CAPTIONING("\uf20a"),
  FA_COMMENT("\uf075"),
  FA_COMMENT_ALT("\uf27a"),
  FA_COMMENT_DOTS("\uf4ad"),
  FA_COMMENTS("\uf086"),
  FA_COMPASS("\uf14e"),
  FA_COPY("\uf0c5"),
  FA_COPYRIGHT("\uf1f9"),
  FA_CREDIT_CARD("\uf09d"),
  FA_DOT_CIRCLE("\uf192"),
  FA_EDIT("\uf044"),
  FA_ENVELOPE("\uf0e0"),
  FA_ENVELOPE_OPEN("\uf2b6"),
  FA_EYE("\uf06e"),
  FA_EYE_SLASH("\uf070"),
  FA_FILE("\uf15b"),
  FA_FILE_ALT("\uf15c"),
  FA_FILE_ARCHIVE("\uf1c6"),
  FA_FILE_AUDIO("\uf1c7"),
  FA_FILE_CODE("\uf1c9"),
  FA_FILE_EXCEL("\uf1c3"),
  FA_FILE_IMAGE("\uf1c5"),
  FA_FILE_PDF("\uf1c1"),
  FA_FILE_POWERPOINT("\uf1c4"),
  FA_FILE_VIDEO("\uf1c8"),
  FA_FILE_WORD("\uf1c2"),
  FA_FLAG("\uf024"),
  FA_FOLDER("\uf07b"),
  FA_FOLDER_OPEN("\uf07c"),
  FA_FROWN("\uf119"),
  FA_FUTBOL("\uf1e3"),
  FA_GEM("\uf3a5"),
  FA_HAND_LIZARD("\uf258"),
  FA_HAND_PAPER("\uf256"),
  FA_HAND_PEACE("\uf25b"),
  FA_HAND_POINT_DOWN("\uf0a7"),
  FA_HAND_POINT_LEFT("\uf0a5"),
  FA_HAND_POINT_RIGHT("\uf0a4"),
  FA_HAND_POINT_UP("\uf0a6"),
  FA_HAND_POINTER("\uf25a"),
  FA_HAND_ROCK("\uf255"),
  FA_HAND_SCISSORS("\uf257"),
  FA_HAND_SPOCK("\uf259"),
  FA_HANDSHAKE("\uf2b5"),
  FA_HDD("\uf0a0"),
  FA_HEART("\uf004"),
  FA_HOSPITAL("\uf0f8"),
  FA_HOURGLASS("\uf254"),
  FA_ID_BADGE("\uf2c1"),
  FA_ID_CARD("\uf2c2"),
  FA_IMAGE("\uf03e"),
  FA_IMAGES("\uf302"),
  FA_KEYBOARD("\uf11c"),
  FA_LEMON("\uf094"),
  FA_LIFE_RING("\uf1cd"),
  FA_LIGHTBULB("\uf0eb"),
  FA_LIST_ALT("\uf022"),
  FA_MAP("\uf279"),
  FA_MEH("\uf11a"),
  FA_MINUS_SQUARE("\uf146"),
  FA_MONEY_BILL_ALT("\uf3d1"),
  FA_MOON("\uf186"),
  FA_NEWSPAPER("\uf1ea"),
  FA_OBJECT_GROUP("\uf247"),
  FA_OBJECT_UNGROUP("\uf248"),
  FA_PAPER_PLANE("\uf1d8"),
  FA_PAUSE_CIRCLE("\uf28b"),
  FA_PLAY_CIRCLE("\uf144"),
  FA_PLUS_SQUARE("\uf0fe"),
  FA_QUESTION_CIRCLE("\uf059"),
  FA_REGISTERED("\uf25d"),
  FA_SAVE("\uf0c7"),
  FA_SHARE_SQUARE("\uf14d"),
  FA_SMILE("\uf118"),
  FA_SNOWFLAKE("\uf2dc"),
  FA_SQUARE("\uf0c8"),
  FA_STAR("\uf005"),
  FA_STAR_HALF("\uf089"),
  FA_STICKY_NOTE("\uf249"),
  FA_STOP_CIRCLE("\uf28d"),
  FA_SUN("\uf185"),
  FA_THUMBS_DOWN("\uf165"),
  FA_THUMBS_UP("\uf164"),
  FA_TIMES_CIRCLE("\uf057"),
  FA_TRASH_ALT("\uf2ed"),
  FA_USER("\uf007"),
  FA_USER_CIRCLE("\uf2bd"),
  FA_WINDOW_CLOSE("\uf410"),
  FA_WINDOW_MAXIMIZE("\uf2d0"),
  FA_WINDOW_MINIMIZE("\uf2d1"),
  FA_WINDOW_RESTORE("\uf2d2");

  private final String chr;

  FARegularGlyph(final String value)
  {
    this.chr = value;
  }

  @Override
  public String chr()
  {
    return chr;
  }
}
